#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.11"
# dependencies = ["requests", "pillow", "pyyaml"]
# ///
"""Fetch and optimize preview thumbnails for the talks page.

For every YouTube recording and Google Slides deck in _data/talks.yaml
and _data/interviews.yaml, download the source thumbnail once and emit
two locally-hosted WebP renditions:

    assets/thumbs/video/<id>-320.webp   (~180px tall, slow networks)
    assets/thumbs/video/<id>-640.webp   (desktop / high-DPI)
    assets/thumbs/slides/<id>-320.webp / -640.webp

plus _data/thumbs.yaml recording each thumbnail's real large-rendition
pixel size (srcset descriptors must state true widths). Templates only
reference thumbnails present in the manifest, so unfetchable ones
(access-restricted decks) degrade to a plain tile at build time.

Re-run after adding talks; existing files are refetched only if their
outputs are missing.
"""

import io
import pathlib
import re
import sys
from concurrent.futures import ThreadPoolExecutor

import requests
import yaml
from PIL import Image

VIDEO_DIR = pathlib.Path("assets/thumbs/video")
SLIDES_DIR = pathlib.Path("assets/thumbs/slides")
MANIFEST = pathlib.Path("_data/thumbs.yaml")
QUALITY = 70

YT_RE = re.compile(r"(?:youtu\.be/|watch\?v=)([\w-]+)")
PRES_RE = re.compile(r"presentation/d/(?!e/)([\w-]+)")
RKEY_RE = re.compile(r"resourcekey=([\w-]+)")


def collect() -> tuple[set[str], dict[str, str | None]]:
    videos: set[str] = set()
    slides: dict[str, str | None] = {}
    talks = yaml.safe_load(pathlib.Path("_data/talks.yaml").read_text())
    interviews = yaml.safe_load(pathlib.Path("_data/interviews.yaml").read_text())
    for entry in talks + interviews:
        m = YT_RE.search(entry.get("video") or "")
        if m:
            videos.add(m.group(1))
        embed = entry.get("slides_embed") or ""
        m = PRES_RE.search(embed)
        if m:
            rk = RKEY_RE.search(embed)
            slides[m.group(1)] = rk.group(1) if rk else None
    return videos, slides


def emit(img: Image.Image, base: pathlib.Path) -> dict:
    img = img.convert("RGB")
    large = img if img.width <= 640 else img.resize(
        (640, round(img.height * 640 / img.width)), Image.LANCZOS)
    small = img.resize((320, round(img.height * 320 / img.width)),
                       Image.LANCZOS) if img.width > 320 else img
    large.save(f"{base}-640.webp", "WEBP", quality=QUALITY)
    small.save(f"{base}-320.webp", "WEBP", quality=QUALITY)
    return {"w": large.width, "h": large.height}


def fetch_video(vid: str) -> tuple[str, dict] | None:
    base = VIDEO_DIR / vid
    for name in ("hq720.jpg", "hqdefault.jpg"):
        r = requests.get(f"https://i.ytimg.com/vi/{vid}/{name}", timeout=20)
        if r.ok and r.content[:3] == b"\xff\xd8\xff":
            img = Image.open(io.BytesIO(r.content))
            if name == "hqdefault.jpg":  # 480x360 letterboxed: crop to 16:9
                img = img.crop((0, 45, 480, 315))
            return vid, emit(img, base)
    print(f"video {vid}: no thumbnail", file=sys.stderr)
    return None


def fetch_slides(item: tuple[str, str | None]) -> tuple[str, dict] | None:
    pid, rkey = item
    url = f"https://drive.google.com/thumbnail?id={pid}&sz=w640"
    if rkey:
        url += f"&resourcekey={rkey}"
    r = requests.get(url, timeout=20, allow_redirects=True)
    if r.ok and r.content[:4] in (b"\xff\xd8\xff\xe0", b"\xff\xd8\xff\xdb",
                                  b"\x89PNG", b"RIFF") or (
            r.ok and r.headers.get("content-type", "").startswith("image/")):
        try:
            img = Image.open(io.BytesIO(r.content))
        except Exception as exc:
            print(f"slides {pid}: undecodable ({exc})", file=sys.stderr)
            return None
        return pid, emit(img, SLIDES_DIR / pid)
    print(f"slides {pid}: HTTP {r.status_code}", file=sys.stderr)
    return None


def main() -> None:
    VIDEO_DIR.mkdir(parents=True, exist_ok=True)
    SLIDES_DIR.mkdir(parents=True, exist_ok=True)
    videos, slides = collect()
    with ThreadPoolExecutor(8) as pool:
        vids = [r for r in pool.map(fetch_video, sorted(videos)) if r]
        decks = [r for r in pool.map(fetch_slides, sorted(slides.items())) if r]
    manifest = {
        "video": {k: v for k, v in sorted(vids)},
        "slides": {k: v for k, v in sorted(decks)},
    }
    MANIFEST.write_text(
        "# Generated by scripts/fetch_talk_thumbs.py — do not hand-edit.\n"
        "# w/h are the -640 rendition's true pixel size (for srcset/width).\n"
        + yaml.safe_dump(manifest, sort_keys=True, allow_unicode=True))
    print(f"videos: {len(vids)}/{len(videos)}  "
          f"slides: {len(decks)}/{len(slides)}", file=sys.stderr)


if __name__ == "__main__":
    main()
